# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

schedules:
- cron: 10 18 * * Mon # mm HH DD MM DW
  displayName: Localization update
  branches:
    include: 
    - master
  always: true

pool:
  vmImage: 'Ubuntu-latest'

steps:

- powershell: |
    $buildUrl = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary"
    echo $buildUrl

#- task: InstallAppleProvisioningProfilem@1
#  inputs:
#    provisioningProfileLocation: 'secureFiles'
#    provProfileSecureFile: 'test.mobileprovision'
#    #provProfileSourceRepository: 'test.mobileprovision'
#    removeProfile: true

#- task: Bash@3
#  displayName: "Check if provisioning profile installed"
#  inputs:
#    targetType: 'inline'
#    script: |
#      cd "$HOME/Library/MobileDevice/Provisioning Profiles"
#      security cms -D -i B5C2906D-D6EE-476E-AF17-D99AE14644AA.mobileprovision

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'node --version'
