# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'Windows-latest'

steps:

- bash: |
    which mvn

#- task: InstallAppleProvisioningProfilem@1
#  inputs:
#    provisioningProfileLocation: 'secureFiles'
#    provProfileSecureFile: 'test.mobileprovision'
#    #provProfileSourceRepository: 'test.mobileprovision'
#    removeProfile: true

#- task: Bash@3
#  displayName: "Check if provisioning profile installed"
#  inputs:
#    targetType: 'inline'
#    script: |
#      cd "$HOME/Library/MobileDevice/Provisioning Profiles"
#      security cms -D -i B5C2906D-D6EE-476E-AF17-D99AE14644AA.mobileprovision

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'node --version'
